# Generated by Django 2.1.7 on 2019-05-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
