# Generated by Django 2.1.7 on 2019-06-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
