# Generated by Django 2.1.7 on 2019-05-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_macarons_pic_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macarons',
            old_name='pic_title',
            new_name='pic_content',
        ),
    ]
