# Generated by Django 2.1.7 on 2019-05-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190522_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macarons',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
    ]
