# Generated by Django 2.2.2 on 2019-06-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20190608_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macarons',
            name='pic_content',
            field=models.CharField(max_length=500),
        ),
    ]
