# Generated by Django 2.2.2 on 2019-06-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20190608_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macarons',
            name='pic_content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_pic',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
