# Generated by Django 2.2.2 on 2019-06-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20190608_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macarons',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='macarons',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='macarons',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='num',
            field=models.CharField(default='', max_length=20),
        ),
    ]
