# Generated by Django 2.2.2 on 2019-06-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20190608_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macarons',
            name='price',
            field=models.IntegerField(),
        ),
    ]
