# Generated by Django 2.2.2 on 2019-06-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20190608_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macarons',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='macarons',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
