# Generated by Django 2.2.1 on 2019-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(help_text='제목을 입력해주세요.', max_length=50)),
                ('content', models.TextField(help_text='내용을 입력해주세요.', max_length=500)),
            ],
        ),
    ]
