# Generated by Django 2.1.7 on 2019-06-09 21:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('writer', models.CharField(default='', max_length=100)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(help_text='Title of review', max_length=50, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Content of review', max_length=500)),
                ('rate', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=10)),
                ('store', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
