# Generated by Django 2.2.1 on 2019-05-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_type',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
