# Generated by Django 2.1.7 on 2019-05-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190530_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.BooleanField(default=False, help_text='Flag if user is owner = true', null=True),
        ),
    ]
