# Generated by Django 2.2.2 on 2019-06-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_pic',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
