# Generated by Django 2.2.2 on 2019-06-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20190608_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_pic',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
