# Generated by Django 2.2.2 on 2019-06-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20190608_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macarons',
            name='picture',
            field=models.ImageField(upload_to='pictures/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_pic',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
