# Generated by Django 2.2.2 on 2019-06-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20190608_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macarons',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='num',
            field=models.CharField(max_length=20),
        ),
    ]
