# Generated by Django 2.2.2 on 2019-06-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20190608_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macarons',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='macarons',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
