# Generated by Django 2.2.1 on 2019-05-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resevation',
            fields=[
                ('reser_num', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=128)),
                ('shop_name', models.CharField(max_length=128)),
                ('macaron_name', models.CharField(max_length=128)),
                ('macaron_num', models.IntegerField()),
                ('macaron_price', models.IntegerField()),
                ('reser_request_time', models.DateTimeField()),
                ('reser_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
