# Generated by Django 2.2.1 on 2019-05-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resevation',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resevation',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
