# Generated by Django 2.1.7 on 2019-05-31 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0002_auto_20190520_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reser_num', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.IntegerField(default=0)),
                ('reser_request_time', models.DateTimeField()),
                ('reser_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='resevation',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Resevation',
        ),
    ]
