# Generated by Django 2.2.1 on 2019-06-04 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_store_owner'),
        ('reservation', '0003_auto_20190531_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='choice_macaron',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='shop_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
