# Generated by Django 2.2.1 on 2019-06-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20190605_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
