# Generated by Django 2.2.1 on 2019-06-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20190608_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reser_num',
            field=models.IntegerField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
