# Generated by Django 2.2.1 on 2019-06-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190604_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='choice_macaron',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
