# Generated by Django 2.2.1 on 2019-06-05 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20190605_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='choice_macaron',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reser_num',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reser_request_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reser_time',
            field=models.DateTimeField(),
        ),
    ]
