# Generated by Django 2.2.1 on 2019-06-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20190609_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reser_num',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
